import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Instrument_Serif } from "next/font/google";
import "./globals.css";

// Stopgap: riffle.dev is still parked at the registrar, so absolute URLs
// built from it (og:image above all) resolve to a lander instead of this
// site. Points at the Vercel domain until riffle.dev is attached to the
// project, then goes back to "https://riffle.dev".
const url = "https://rifffle.vercel.app";
const title = "Riffle — review what matters first";
const description =
  "Riffle is an open-source GitHub App, in development, that ranks your pull request queue by risk — trained on your own repository's history.";

// Display serif for the tagline. High-contrast, genuinely distinctive at
// large sizes, and contemporary — editorial presence against the painting
// without reading as period pastiche.
const tagline = Instrument_Serif({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-tagline",
});

const supplyMono = localFont({
  src: [
    { path: "../public/fonts/PPSupplyMono-Regular.woff2", weight: "400" },
    { path: "../public/fonts/PPSupplyMono-Ultralight.woff2", weight: "200" },
  ],
  display: "swap",
  variable: "--font-supply-mono",
});

export const metadata: Metadata = {
  metadataBase: new URL(url),
  title,
  description,
  // iOS ignores SVG touch icons, so the apple icon is a PNG.
  icons: { icon: "/favicon.svg", apple: "/apple-touch-icon.png" },
  // The social card is generated by app/opengraph-image.tsx; the file
  // convention emits og:image and twitter:image with their dimensions, so
  // listing images here would only duplicate those tags.
  openGraph: {
    title,
    description,
    url,
    siteName: "Riffle",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
};

export const viewport: Viewport = { themeColor: "#14100c" };

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Riffle",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Any",
  description,
  url,
  license: "https://www.apache.org/licenses/LICENSE-2.0",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

const criticalCss = `
html,body{height:100%;margin:0;background:#14100c}
body{color:#f4f5f7}
/* /v2 is a light document; set here so it cannot flash dark pre-stylesheet */
body:has([data-riffle-light]){background:#fbfaf7;color:#16171d}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${tagline.variable} ${GeistSans.variable} ${GeistMono.variable} ${supplyMono.variable}`}
      // The motion script below sets data-motion on this element before
      // hydration, by design - it has to run before first paint. That makes
      // the server and client attribute sets differ, which is exactly what
      // this suppresses. Scoped to <html>, so mismatches anywhere else still
      // report. Browser extensions that decorate <html> stop warning too.
      suppressHydrationWarning
    >
      <head>
        <style dangerouslySetInnerHTML={{ __html: criticalCss }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
