import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

// Stopgap: riffle.dev is still parked at the registrar, so absolute URLs
// built from it (og:image above all) resolve to a lander instead of this
// site. Points at the Vercel domain until riffle.dev is attached to the
// project, then goes back to "https://riffle.dev".
const url = "https://rifffle.vercel.app";
const title = "Riffle — review what matters first";
const description =
  "Riffle is an open-source GitHub App, in development, that ranks your pull request queue by risk — trained on your own repository's history.";



export const metadata: Metadata = {
  metadataBase: new URL(url),
  title,
  description,
  // iOS ignores SVG touch icons, so the apple icon is a PNG.
  icons: { icon: "/favicon.svg", apple: "/apple-touch-icon.png" },
  // The social card is generated by app/opengraph-image.tsx; the file
  // convention emits og:image and twitter:image with their dimensions, so
  // listing images here would only duplicate those tags.
  openGraph: {
    title,
    description,
    url,
    siteName: "Riffle",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
};

export const viewport: Viewport = { themeColor: "#fbfaf7" };

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Riffle",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Any",
  description,
  url,
  license: "https://www.apache.org/licenses/LICENSE-2.0",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

const criticalCss = `
html,body{height:100%;margin:0;background:#fbfaf7}
body{color:#16171d}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      // The motion component sets data-motion-ready here, and browser
      // extensions decorate <html>; neither is a real mismatch. Scoped to
      // <html>, so mismatches anywhere else still report.
      suppressHydrationWarning
    >
      <head>
        {/* href + precedence make this a React style resource: hoisted and
            deduplicated rather than matched tag-by-tag during hydration, so
            an extension that prepends its own <style> to <head> (Ant Design
            based ones do) no longer breaks hydration. */}
        <style href="rf-critical" precedence="high">
          {criticalCss}
        </style>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
